apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyclaim-backend
  labels:
    name: easyclaim-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: easyclaim-backend
  template:
    metadata:
      name: easyclaim-backend
      labels:
        name: easyclaim-backend
    spec:
      containers:
        - name:  easyclaim-backend
          image: vigneshsweekaran/easyclaim-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
