apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: easyclaim-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: easyclaim-backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50