apiVersion: v1
kind: Service
metadata:
  name: easyclaim-backend
  labels:
    name: easyclaim-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32012
  selector:
    name: easyclaim-backend
  type: NodePort
